"""The Inventory contract.

One source of truth for "is this inventory data valid". Everything that
loads, edits, or saves inventory data routes through this module:
engine, builder, tests. No other call site is allowed to construct an
``Inventory`` from raw fields -- only ``parse``, ``from_grid``, or
``load`` accept untrusted data, and each of those funnels through
``parse`` so the validation code path is singular.

Parse-don't-validate: ``parse`` either returns a fully-normalized
``Inventory`` whose invariants are guaranteed to hold for the life of
the value, or raises ``ValidationError`` carrying every problem it
found (not just the first). Downstream code never has to re-check.

The instance is structurally immutable: ``features`` is a tuple,
``segments`` is a ``MappingProxyType`` of ``MappingProxyType``. Holders
may store the value directly without a defensive copy because the
caller cannot mutate it after construction. "Edits" are done by
constructing a new ``Inventory``.

Writes go through ``write_atomic`` which uses a tmp file + ``os.replace``
so a crash mid-write never leaves a truncated JSON on disk.
"""

from __future__ import annotations

import json
import os
import tempfile
import unicodedata
from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Any

from phonology_features._logging import get_logger

_log = get_logger(__name__)

VALID_VALUES: frozenset[str] = frozenset({"+", "-", "0"})

# ---------------------------------------------------------------------
# Name identity policy
#
# Feature and segment names are KEYS, not display strings. The parser
# is the only place that decides when two external spellings are "the
# same name." Once Inventory.parse returns, every downstream consumer
# (engine indexes, GUI widgets, save round-trip) trusts that names are
# already canonical, unique, and bounded.
#
# Canonical form for a name:
#   1. NFC-normalize (so "é" precomposed and "é" = "e" + combining
#      acute compare equal -- they LOOK identical to the user).
#   2. Strip leading/trailing whitespace (often accidental, especially
#      trailing -- invisible in most editors).
#   3. Reject empty-after-strip.
#   4. Reject canonical-collisions: if both "Voice" and " Voice " or
#      both "é" (NFC) and "é" (NFD) appear in one inventory, that's
#      ambiguous user intent -- report rather than silently merge.
#
# Canonical form for the inventory:
#   5. Reject duplicate JSON object keys at decode time -- once
#      json.load returns a dict, duplicates are silently lost.
#   6. Reject alias collisions on the engine's _normalize_key (e.g.
#      "DelRel" vs "delayed_release") -- otherwise grouped_segments
#      would crash downstream.
#   7. Enforce length caps so a 10k-char paste cannot degrade the UI,
#      logs, or validation reports.
#
# Soft advisories (not rejected): surfaced to the user but allowed.
# These are unusual-but-valid configurations, not errors.
# ---------------------------------------------------------------------

# Hard caps. Generous enough that no realistic phonological inventory
# is constrained; small enough to catch obvious accidents (a paragraph
# pasted into a name field, an autogenerated 100k-segment stress file).
MAX_NAME_LENGTH: int = 256
MAX_FEATURES: int = 100
MAX_SEGMENTS: int = 1000

# Soft thresholds. Bundled inventories must stay BELOW these so they
# don't trigger advisories on every load. General (the largest
# bundled) is 135 segments × 30 features.
ADVISORY_SEGMENT_THRESHOLD: int = 200
ADVISORY_FEATURE_THRESHOLD: int = 50


# Domain-specific identity folding for segment labels: ASCII
# characters that users routinely type as substitutes for IPA
# characters are folded to the canonical IPA form so two spellings
# produce one segment. Applied AFTER ``_canonicalize_name`` (NFC +
# strip) and BEFORE the identity-collision check, so an inventory
# containing both ``g`` and ``ɡ`` is correctly reported as a
# duplicate-after-normalization rather than silently kept as two.
#
# Applied to segment labels ONLY -- feature names are analytical
# identifiers (not IPA notation) and the inventory name is a
# display label.
#
# ``r`` is deliberately excluded. ``r`` IS the legitimate IPA
# alveolar trill character; folding it to ``ɹ`` (turned r, the
# approximant) would silently change the meaning.
# ``:`` is not folded but kept as an advisory (``_ipa_confusable_notes``
# below) -- it's much more likely a paste mistake than a deliberate
# choice, but the cost of getting it wrong is high (changes vowel
# length semantics), so we inform rather than rewrite.
_IPA_SEGMENT_TRANSLATIONS: dict[str, str] = {
    "'": "ʼ",  # APOSTROPHE → MODIFIER LETTER APOSTROPHE (ejective)
    "g": "ɡ",  # ASCII g → LATIN SMALL LETTER SCRIPT G (voiced velar)
}
_IPA_TRANSLATION_TABLE = str.maketrans(_IPA_SEGMENT_TRANSLATIONS)


def _ipa_normalize_segment(canonical: str) -> str:
    """Fold the small set of ASCII substitutes that users commonly
    type instead of canonical IPA characters in segment labels.
    Idempotent. Pure transformation -- no validation."""
    return canonical.translate(_IPA_TRANSLATION_TABLE)


def _ipa_confusable_notes(canonical_seg: str) -> list[str]:
    """Return advisory notes for IPA-confusable characters in the
    segment label. ADVISORY ONLY -- never an error. Used to surface
    common paste-source mistakes (ASCII colon used where the user
    probably meant the IPA length mark).

    Scope is deliberately narrow. The essay's broader curated set
    (g/ɡ, '/ʼ, r/ɹ) was verified against the bundled inventories
    and would produce false positives on every load (Hayes and
    Blevins use literal 'g' in 'g͡b'; the General inventory uses
    ASCII apostrophe for ejectives; 'r' is the legitimate IPA
    alveolar trill character, not a confusable). ASCII colon is the
    one hazard that has no realistic legitimate use in IPA segment
    labels -- if it appears it's almost always a typing substitute
    for U+02D0 MODIFIER LETTER TRIANGULAR COLON.
    """
    notes: list[str] = []
    if ":" in canonical_seg:
        notes.append(
            f"segment {canonical_seg!r} contains U+003A COLON; if you "
            f"intended the IPA length mark, the canonical code point is "
            f"U+02D0 MODIFIER LETTER TRIANGULAR COLON (ː)"
        )
    return notes


def _canonicalize_name(s: str) -> str:
    """Apply the name-identity canonicalization: NFC, then strip
    leading/trailing whitespace. The returned string is what the
    parser stores as the key.

    NFC (not NFKC) is deliberate: NFC merges canonical equivalents
    that look identical (precomposed vs combining), while NFKC also
    folds compatibility variants that may carry phonetic or
    orthographic meaning (e.g. ligatures, half-width forms).

    ``str.strip()`` is Unicode-aware for whitespace (NBSP, NNBSP, etc.)
    but does NOT strip Unicode FORMAT characters (ZWJ, ZWNJ, LRM, RLM,
    BOM). Those survive canonicalization and create truly invisible
    distinct keys, so they're rejected separately via
    ``_invisible_format_chars`` rather than silently stripped.
    """
    return unicodedata.normalize("NFC", s).strip()


# Unicode general categories rejected inside canonical names. All
# three classes share the "no legitimate use in a phonological
# identifier and creates a hidden hazard if accepted":
#   Cf -- FORMAT (ZWJ, ZWNJ, LRM, RLM, BOM): invisible, survive
#         NFC + strip, create distinct keys that LOOK identical.
#   Cs -- SURROGATE (lone halves like U+DCFF): NFC accepts them,
#         but ``str.encode('utf-8')`` raises "surrogates not
#         allowed" -- the inventory loads but every save fails
#         (save lockout). Reject at parse so the user never reaches
#         that state.
#   Cc -- CONTROL (NUL, BEL, BS, FF, VT, CR, LF, TAB inside a
#         name): ``str.strip()`` only removes Cc at edges, not in
#         the middle. Hand-edited JSON could embed them, leading to
#         odd rendering in the grid, validation reports, and logs.
_DISALLOWED_NAME_CATEGORIES: frozenset[str] = frozenset({"Cf", "Cs", "Cc"})


def _invisible_format_chars(s: str) -> list[str]:
    """Return any Unicode characters in ``s`` whose general category
    is in ``_DISALLOWED_NAME_CATEGORIES`` (format, surrogate, or
    control). Empty when the string contains none.

    Each entry is human-readable: code point + Unicode name (or
    ``UNNAMED`` for code points without one, such as some
    surrogates). The caller embeds them in a ValidationError
    message so the user can locate and remove the offender.

    Function name kept for compatibility with existing callers;
    its scope is now broader than purely "invisible" -- it also
    rejects surrogate code points that would save-lock the file
    and embedded controls that would render oddly.
    """
    found: list[str] = []
    for ch in s:
        if unicodedata.category(ch) in _DISALLOWED_NAME_CATEGORIES:
            try:
                cp_name = unicodedata.name(ch)
            except ValueError:
                cp_name = "UNNAMED"
            found.append(f"U+{ord(ch):04X} ({cp_name})")
    return found


class _DuplicateJSONKey(ValueError):
    """Raised from ``_no_duplicate_keys`` when ``json.load`` sees the
    same key twice in one object literal. The default dict-merge
    behaviour silently keeps the last value, so an inventory file
    with two copies of the same segment loses one without warning --
    classic pre-parser data loss. Caught at the ``Inventory.load``
    boundary and rewrapped as ``ValidationError``."""

    def __init__(self, keys: list[str]):
        self.keys = keys
        super().__init__(
            f"duplicate JSON key(s) -- earlier value would be silently "
            f"discarded: {sorted(set(keys))!r}"
        )


def _no_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    """``object_pairs_hook`` for ``json.load``. Rejects duplicate keys
    rather than letting Python's dict construction silently keep the
    last value. Fires at decode time -- before any Inventory.parse
    check -- because once json.load returns a dict, the evidence is
    gone."""
    seen: dict[str, Any] = {}
    duplicates: list[str] = []
    for k, v in pairs:
        if k in seen:
            duplicates.append(k)
        seen[k] = v
    if duplicates:
        raise _DuplicateJSONKey(duplicates)
    return seen


# Inventory file format version. Bumped when the on-disk shape changes
# in a way old readers cannot understand. Files written by this version
# always include ``schema_version`` at the top level. Files written by
# previous versions omitted the field; reads treat the absence as
# ``CURRENT_SCHEMA_VERSION`` so existing bundled and user inventories
# load without migration.
#
# When you add version 2: keep version 1 in ``SUPPORTED_SCHEMA_VERSIONS``
# until at least one release has shipped the migration path, then drop
# it. Reading an unsupported version raises ``ValidationError`` with a
# clear message rather than guessing.
CURRENT_SCHEMA_VERSION: int = 1
SUPPORTED_SCHEMA_VERSIONS: frozenset[int] = frozenset({1})


class ValidationError(Exception):
    """Raised by ``Inventory.parse`` when the input is not a valid
    inventory. Carries every problem found (not just the first) so a
    GUI surface can show the full list at once.

    ``str(err)`` is the first issue -- useful for status bars.
    ``err.issues`` is the full tuple, in the order the parser found
    them (top-level shape first, then per-feature, then per-segment,
    then per-cell).
    """

    def __init__(self, issues: tuple[str, ...]):
        if not issues:
            issues = ("Invalid inventory (no issue detail)",)
        self.issues: tuple[str, ...] = issues
        super().__init__(issues[0])


@dataclass(frozen=True)
class Inventory:
    """A validated phonological inventory.

    Fields:
      - ``name``: human-readable display name; never empty
      - ``metadata``: arbitrary metadata mapping (read-only view)
      - ``features``: declared feature names, in their declared order;
        non-empty strings, unique
      - ``segments``: ``{symbol: {feature: value}}``; symbols are
        non-empty strings, feature keys are a subset of ``features``,
        values are in ``VALID_VALUES``. Inner maps are read-only views.

    Missing-feature semantics: a segment's bundle may omit a declared
    feature; readers should treat the omission as ``"0"``. The parser
    does NOT auto-fill the omission because round-tripping should not
    silently inflate the on-disk file.
    """

    name: str
    metadata: Mapping[str, Any]
    features: tuple[str, ...]
    segments: Mapping[str, Mapping[str, str]]
    # Soft observations the parser collected. Empty for typical
    # inventories. NOT errors -- the inventory loaded successfully --
    # but worth surfacing in the UI status bar so the user knows when
    # they're outside the usual operating range (e.g. unusually large
    # segment or feature counts). Kept on the Inventory rather than
    # computed on-demand so the parser remains the single source of
    # truth for "what's noteworthy about this inventory."
    advisories: tuple[str, ...] = field(default=())

    @classmethod
    def parse(cls, raw: Any, *, source: str | None = None) -> Inventory:
        """Validate raw (already-JSON-decoded) data into an Inventory.

        Collects every issue before raising so the caller can show them
        all. ``source`` is included in error messages when provided
        (typically a file path) to help disambiguate when the GUI is
        loading multiple inventories.
        """
        issues: list[str] = []
        prefix = f"{source}: " if source else ""

        if not isinstance(raw, dict):
            raise ValidationError(
                (
                    f"{prefix}top-level JSON value must be an object, "
                    f"got {type(raw).__name__}",
                )
            )

        # ----- schema version -----
        # Checked BEFORE per-field validation: if we can't read the
        # format, every subsequent issue is meaningless. Missing is
        # treated as version 1 so files written before this field was
        # introduced load without migration.
        if "schema_version" in raw:
            sv = raw["schema_version"]
            # bool is a subclass of int; reject it explicitly so True
            # / False can't sneak through as "schema_version 1".
            if isinstance(sv, bool) or not isinstance(sv, int):
                raise ValidationError(
                    (
                        f"{prefix}'schema_version' must be an integer, "
                        f"got {type(sv).__name__}",
                    )
                )
            if sv not in SUPPORTED_SCHEMA_VERSIONS:
                supported = ", ".join(
                    str(v) for v in sorted(SUPPORTED_SCHEMA_VERSIONS)
                )
                raise ValidationError(
                    (
                        f"{prefix}unsupported schema_version {sv}; "
                        f"this build reads version(s) {supported}",
                    )
                )

        # ----- features -----
        if "features" not in raw:
            issues.append(f"{prefix}missing required key 'features'")
            features_tuple: tuple[str, ...] = ()
            declared: set[str] = set()
        else:
            features_raw = raw["features"]
            features_tuple, declared = _validate_features(
                features_raw, issues, prefix
            )

        # ----- segments -----
        if "segments" not in raw:
            issues.append(f"{prefix}missing required key 'segments'")
            segments_view: Mapping[str, Mapping[str, str]] = MappingProxyType(
                {}
            )
        else:
            segments_raw = raw["segments"]
            segments_view = _validate_segments(
                segments_raw, declared, issues, prefix
            )

        if issues:
            raise ValidationError(tuple(issues))

        # Collect metadata from BOTH conventions: an explicit
        # ``metadata`` object (Hayes shape) AND any top-level extras
        # like ``name``/``version``/``notes`` that bundled files store
        # at the root (general_features shape). The explicit metadata
        # object wins on key collision so callers can override.
        metadata: dict[str, Any] = {}
        for key, value in raw.items():
            # ``schema_version`` lives at the top level for tooling
            # visibility; never duplicate it into metadata or it would
            # round-trip into two places on save.
            if key in ("features", "segments", "metadata", "schema_version"):
                continue
            metadata[key] = value
        explicit_metadata = raw.get("metadata")
        if isinstance(explicit_metadata, dict):
            metadata.update(explicit_metadata)
        # Inventory name is a display label, not a key, so the policy
        # is lighter than segment/feature names: canonicalize and cap,
        # but skip the alias/collision/invisible-char checks. Length
        # cap protects the title bar and meta strip from a pasted
        # paragraph.
        raw_name = metadata.get("name")
        if isinstance(raw_name, str):
            canonical_name = _canonicalize_name(raw_name)
        else:
            canonical_name = ""
        if not canonical_name:
            canonical_name = "Untitled Inventory"
        if len(canonical_name) > MAX_NAME_LENGTH:
            canonical_name = canonical_name[:MAX_NAME_LENGTH]
        name = canonical_name
        # Ensure name round-trips even when the input had none, and
        # that the on-disk metadata reflects the canonical form.
        metadata["name"] = name

        # Soft advisories: notable-but-valid observations surfaced to
        # the user but not blocking. Pure cardinality only -- no
        # semantic interpretation of what's "useful" or "specified"
        # (underspecification with '0' is a real linguistic concept).
        advisories: list[str] = []
        if len(segments_view) > ADVISORY_SEGMENT_THRESHOLD:
            advisories.append(
                f"unusually large inventory: {len(segments_view)} segments "
                f"(typical max ~{ADVISORY_SEGMENT_THRESHOLD})"
            )
        if len(features_tuple) > ADVISORY_FEATURE_THRESHOLD:
            advisories.append(
                f"unusually large feature set: {len(features_tuple)} "
                f"features (typical max ~{ADVISORY_FEATURE_THRESHOLD})"
            )
        # Curated IPA-confusable advisories on segment labels.
        # Narrow (just ASCII colon) by design -- see
        # ``_ipa_confusable_notes`` for why.
        for canonical_seg in segments_view:
            advisories.extend(_ipa_confusable_notes(canonical_seg))

        return cls(
            name=name,
            metadata=MappingProxyType(metadata),
            features=features_tuple,
            segments=segments_view,
            advisories=tuple(advisories),
        )

    @classmethod
    def from_grid(
        cls,
        *,
        name: str,
        features: list[str],
        segments: dict[str, dict[str, str]],
    ) -> Inventory:
        """Construct from builder grid state. Validates by funneling
        through ``parse`` so there is exactly one validation code path.
        ASCII-minus normalization (Unicode ``−`` -> ``-``) happens
        here because the grid stores the Unicode form for display."""
        normalized_segments: dict[str, dict[str, str]] = {}
        for seg, feats in segments.items():
            normalized: dict[str, str] = {}
            for f, v in feats.items():
                if v == "−":
                    v = "-"
                normalized[f] = v
            normalized_segments[seg] = normalized
        return cls.parse(
            {
                "metadata": {"name": name},
                "features": features,
                "segments": normalized_segments,
            }
        )

    @classmethod
    def load(cls, path: str) -> Inventory:
        """Read and parse a JSON inventory file. Raises
        ``ValidationError`` (with ``source=path`` in messages) on any
        problem; the underlying ``OSError`` / ``JSONDecodeError`` is
        wrapped as a ValidationError so callers only need to handle
        one exception type."""
        basename = os.path.basename(path)
        _log.debug("inventory load start: %s", basename)
        try:
            # ``utf-8-sig`` transparently consumes a leading UTF-8 BOM
            # (``b"\xef\xbb\xbf"``). Files exported from Windows
            # Notepad / Excel / many other tools commonly add one;
            # plain ``utf-8`` would raise ``invalid JSON: Unexpected
            # UTF-8 BOM`` with a cryptic message that tells a linguist
            # nothing actionable. The codec behaves identically to
            # ``utf-8`` for files without a BOM.
            with open(path, encoding="utf-8-sig") as f:
                # object_pairs_hook intercepts each JSON object literal
                # before dict construction so a duplicate key (which a
                # plain json.load would silently collapse to the last
                # value -- pre-parser data loss) is reported instead.
                raw = json.load(f, object_pairs_hook=_no_duplicate_keys)
        except FileNotFoundError as e:
            _log.warning("inventory load failed: %s: file not found", basename)
            raise ValidationError((f"{path}: file not found",)) from e
        except _DuplicateJSONKey as e:
            _log.warning(
                "inventory load failed: %s: duplicate JSON key(s)", basename
            )
            raise ValidationError((f"{path}: {e}",)) from e
        except json.JSONDecodeError as e:
            _log.warning(
                "inventory load failed: %s: invalid JSON (%s line %d)",
                basename,
                e.msg,
                e.lineno,
            )
            raise ValidationError(
                (f"{path}: invalid JSON ({e.msg} on line {e.lineno})",)
            ) from e
        except OSError as e:
            _log.warning("inventory load failed: %s: %s", basename, e)
            raise ValidationError((f"{path}: {e}",)) from e
        try:
            inv = cls.parse(raw, source=path)
        except ValidationError as e:
            _log.warning(
                "inventory validation failed: %s (%d issue%s)",
                basename,
                len(e.issues),
                "" if len(e.issues) == 1 else "s",
            )
            raise
        _log.info(
            "inventory loaded: %s (%d segments, %d features)",
            basename,
            len(inv.segments),
            len(inv.features),
        )
        return inv

    # ----- output -----
    def to_json_dict(self) -> dict[str, Any]:
        """Plain dict suitable for ``json.dump``. Inner views are
        unwrapped to dicts because ``json.dump`` doesn't know about
        ``MappingProxyType``. ``schema_version`` is the first key by
        convention -- tooling that inspects without parsing (jq, grep,
        future migrators) can find it without walking the whole file.
        """
        return {
            "schema_version": CURRENT_SCHEMA_VERSION,
            "metadata": dict(self.metadata),
            "features": list(self.features),
            "segments": {
                seg: dict(feats) for seg, feats in self.segments.items()
            },
        }

    def write_atomic(self, path: str) -> None:
        """Crash-safe write: serialize to a sibling tmp file, then
        ``os.replace`` onto the target. An interrupted run leaves
        either the old file untouched or the new file fully written;
        never a half-written file. External file watchers see one
        atomic rename rather than a series of partial writes.
        """
        atomic_write_json(path, self.to_json_dict())

    # ----- convenience accessors used widely -----
    def feature_value(self, segment: str, feature: str) -> str:
        """Value of ``feature`` for ``segment``. Missing => ``'0'``.
        Raises ``KeyError`` for unknown segment / feature."""
        if segment not in self.segments:
            raise KeyError(f"Segment '{segment}' not in inventory")
        if feature not in self.features:
            raise KeyError(f"Feature '{feature}' not in inventory")
        return self.segments[segment].get(feature, "0")


def _validate_features(
    features_raw: Any, issues: list[str], prefix: str
) -> tuple[tuple[str, ...], set[str]]:
    """Returns (tuple of CANONICAL feature names, set of those names).
    Appends any issues to ``issues``. Names are stored in canonical
    form (NFC + stripped) so downstream lookups never see two
    spellings of the same intended identity."""
    if not isinstance(features_raw, list):
        issues.append(
            f"{prefix}'features' must be a list of strings, "
            f"got {type(features_raw).__name__}"
        )
        return (), set()

    if len(features_raw) > MAX_FEATURES:
        issues.append(
            f"{prefix}'features' has {len(features_raw)} entries; "
            f"hard cap is {MAX_FEATURES}"
        )
        # Don't truncate -- if the file is this far out of bounds, it's
        # almost certainly authored wrong. Return empty so per-feature
        # noise doesn't drown the actionable message.
        return (), set()

    valid: list[str] = []
    seen: set[str] = set()
    # Track the original spelling for each canonical name so a
    # collision message can show the user both forms.
    canonical_origin: dict[str, str] = {}
    for i, f in enumerate(features_raw):
        if not isinstance(f, str):
            issues.append(
                f"{prefix}'features[{i}]' is not a string "
                f"(got {type(f).__name__}: {f!r})"
            )
            continue
        if len(f) > MAX_NAME_LENGTH:
            issues.append(
                f"{prefix}'features[{i}]' is {len(f)} chars; "
                f"max is {MAX_NAME_LENGTH}"
            )
            continue
        canonical = _canonicalize_name(f)
        if not canonical:
            issues.append(
                f"{prefix}'features[{i}]' is empty after canonicalization"
            )
            continue
        invisible = _invisible_format_chars(canonical)
        if invisible:
            issues.append(
                f"{prefix}'features[{i}]' ({f!r}) contains invisible "
                f"format character(s): {invisible}; these have no use "
                f"in feature identifiers and would create distinct keys "
                f"that look identical"
            )
            continue
        if canonical in seen:
            prior = canonical_origin[canonical]
            if prior == f:
                issues.append(f"{prefix}'features' contains duplicate {f!r}")
            else:
                # Two distinct spellings collapsed to the same identity
                # (e.g. " Voice " vs "Voice", or NFC vs NFD of "é").
                issues.append(
                    f"{prefix}features {prior!r} and {f!r} are the same "
                    f"after NFC + whitespace normalization "
                    f"({canonical!r}); rename or remove one"
                )
            continue
        seen.add(canonical)
        canonical_origin[canonical] = f
        valid.append(canonical)

    # Alias-collision check on the engine's _normalize_key (case +
    # delimiter folding). "DelRel" and "delayed_release" are DISTINCT
    # in canonical form (different case + underscores) but engine
    # consumers fold them. Catch at the parser boundary so the engine
    # never has to defend against AliasCollisionError downstream.
    # Lazy import: segment_grouper depends on lru_cache + collections
    # only, no cycle with this module.
    from phonology_features.engine.segment_grouper import _normalize_key

    by_alias: dict[str, list[str]] = {}
    for f in valid:
        by_alias.setdefault(_normalize_key(f), []).append(f)
    for canonical, originals in by_alias.items():
        if len(originals) > 1:
            issues.append(
                f"{prefix}features {sorted(originals)} collide after "
                f"normalization to {canonical!r}; rename or remove one"
            )
    return tuple(valid), seen


def _validate_segments(
    segments_raw: Any,
    declared: set[str],
    issues: list[str],
    prefix: str,
) -> Mapping[str, Mapping[str, str]]:
    """Returns a read-only view of validated segments with CANONICAL
    keys (NFC + stripped). Appends issues. The ``declared`` set is
    expected to already contain canonical feature names so per-bundle
    feature keys can be matched against it after canonicalization."""
    if not isinstance(segments_raw, dict):
        issues.append(
            f"{prefix}'segments' must be an object, "
            f"got {type(segments_raw).__name__}"
        )
        return MappingProxyType({})

    if len(segments_raw) > MAX_SEGMENTS:
        issues.append(
            f"{prefix}'segments' has {len(segments_raw)} entries; "
            f"hard cap is {MAX_SEGMENTS}"
        )
        return MappingProxyType({})

    result: dict[str, Mapping[str, str]] = {}
    canonical_origin: dict[str, str] = {}
    for seg_name, seg_feats in segments_raw.items():
        if not isinstance(seg_name, str) or not seg_name:
            issues.append(
                f"{prefix}segment key {seg_name!r} must be a non-empty string"
            )
            continue
        if len(seg_name) > MAX_NAME_LENGTH:
            issues.append(
                f"{prefix}segment key {seg_name!r} is {len(seg_name)} "
                f"chars; max is {MAX_NAME_LENGTH}"
            )
            continue
        canonical_seg = _canonicalize_name(seg_name)
        if not canonical_seg:
            issues.append(
                f"{prefix}segment key {seg_name!r} is empty after "
                f"canonicalization"
            )
            continue
        # Domain-specific identity folding (ASCII g→ɡ, '→ʼ). Applied
        # AFTER NFC canonicalization but BEFORE the collision check so
        # an inventory containing both "g" and "ɡ" is detected as a
        # duplicate rather than silently kept as two distinct keys.
        canonical_seg = _ipa_normalize_segment(canonical_seg)
        invisible = _invisible_format_chars(canonical_seg)
        if invisible:
            issues.append(
                f"{prefix}segment key {seg_name!r} contains invisible "
                f"format character(s): {invisible}; these would create "
                f"a distinct segment that looks identical to another"
            )
            continue
        if canonical_seg in result:
            prior = canonical_origin[canonical_seg]
            if prior == seg_name:
                issues.append(
                    f"{prefix}segment key {seg_name!r} appears more than once"
                )
            else:
                issues.append(
                    f"{prefix}segments {prior!r} and {seg_name!r} are the "
                    f"same after NFC + whitespace normalization "
                    f"({canonical_seg!r}); rename or remove one"
                )
            continue
        if not isinstance(seg_feats, dict):
            issues.append(
                f"{prefix}segment {canonical_seg!r}: bundle must be an "
                f"object, got {type(seg_feats).__name__}"
            )
            continue
        inner: dict[str, str] = {}
        for feat_name, feat_val in seg_feats.items():
            if not isinstance(feat_name, str) or not feat_name:
                issues.append(
                    f"{prefix}segment {canonical_seg!r}: feature key "
                    f"{feat_name!r} must be a non-empty string"
                )
                continue
            if len(feat_name) > MAX_NAME_LENGTH:
                issues.append(
                    f"{prefix}segment {canonical_seg!r}: feature key "
                    f"{feat_name!r} is {len(feat_name)} chars; max is "
                    f"{MAX_NAME_LENGTH}"
                )
                continue
            canonical_feat = _canonicalize_name(feat_name)
            if not canonical_feat:
                issues.append(
                    f"{prefix}segment {canonical_seg!r}: feature key "
                    f"{feat_name!r} is empty after canonicalization"
                )
                continue
            # No ``if declared and ...`` short-circuit: an inventory
            # with ``features=[]`` AND per-segment feature keys would
            # otherwise be silently accepted, storing ghost data that
            # ``feature_value`` can never reach (raises KeyError
            # because the feature isn't in ``inv.features``). Always
            # cross-check so the contract holds at every count.
            if canonical_feat not in declared:
                issues.append(
                    f"{prefix}segment {canonical_seg!r}: feature "
                    f"{feat_name!r} is not declared in 'features'"
                )
                continue
            if not isinstance(feat_val, str):
                issues.append(
                    f"{prefix}segment {canonical_seg!r}."
                    f"{canonical_feat!r}: value must be a string, got "
                    f"{type(feat_val).__name__} ({feat_val!r})"
                )
                continue
            if feat_val not in VALID_VALUES:
                issues.append(
                    f"{prefix}segment {canonical_seg!r}."
                    f"{canonical_feat!r}: invalid value {feat_val!r} "
                    f"(expected one of {sorted(VALID_VALUES)})"
                )
                continue
            inner[canonical_feat] = feat_val
        result[canonical_seg] = MappingProxyType(inner)
        canonical_origin[canonical_seg] = seg_name
    return MappingProxyType(result)


def atomic_write_json(path: str, data: Any) -> None:
    """Write JSON to ``path`` atomically.

    Writes to a sibling tmp file in the same directory (so the rename
    is a same-filesystem move), fsyncs, then ``os.replace``s. A crash
    or kill anywhere before the replace leaves the destination
    untouched; the rename itself is atomic on POSIX and Windows.

    File watchers see exactly one filesystem event for the destination
    (the rename), not a sequence of write-truncate-write events that
    would each trigger reload.
    """
    basename = os.path.basename(path)
    _log.debug("atomic write start: %s", basename)
    directory = os.path.dirname(os.path.abspath(path)) or "."
    fd, tmp_path = tempfile.mkstemp(
        prefix=".tmp_inv_", suffix=".json", dir=directory
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, path)
    except BaseException as e:
        _log.error("atomic write failed: %s: %s", basename, e)
        try:
            os.remove(tmp_path)
        except OSError:
            pass
        raise
    _log.info("atomic write complete: %s", basename)
