"""Feature preset definitions for the inventory builder."""

FEATURE_PRESETS = {
    "Default (33)": [
        "Syllabic",
        "Consonantal",
        "Sonorant",
        "Approximant",
        "Voice",
        "SpreadGl",
        "ConstrGl",
        "Continuant",
        "Strident",
        "DelRel",
        "Nasal",
        "Lateral",
        "Trill",
        "Tap",
        "Click",
        "LABIAL",
        "Round",
        "Labiodental",
        "CORONAL",
        "Anterior",
        "Distributed",
        "DORSAL",
        "High",
        "Low",
        "Back",
        "Front",
        "Pharyngeal",
        "ATR",
        "Tense",
        "Long",
        "Stress",
        "Tone",
        "UpperRegister",
    ],
    "Custom": [],
}
