"""Shared colour palette for the GUI."""

C = {
    "bg": "#F0F2F5",
    "panel": "#FFFFFF",
    "border": "#D0D5DD",
    "accent": "#2563EB",
    "accent_light": "#DBEAFE",
    "seg_default": "#F8FAFC",
    "seg_selected": "#2563EB",
    "seg_matched": "#2563EB",
    "seg_unmatched": "#E2E8F0",
    "plus": "#15803D",
    "plus_bg": "#DCFCE7",
    "minus": "#B91C1C",
    "minus_bg": "#FEE2E2",
    "shared_plus": "#DCFCE7",
    "shared_minus": "#FEE2E2",
    "text": "#1E293B",
    "text_dim": "#94A3B8",
    "analysis_bg": "#F8FAFC",
    "tag_blue": "#DBEAFE",
    "tag_blue_text": "#1D4ED8",
    "tag_green": "#DCFCE7",
    "tag_green_text": "#15803D",
    "tag_red": "#FEE2E2",
    "tag_red_text": "#B91C1C",
    "tag_gray": "#F1F5F9",
    "tag_gray_text": "#64748B",
}
