"""Hard caps and soft advisory thresholds for inventory data.

All bounds the engine enforces live in this module so a reviewer asking
"what are the contract limits?" finds the answer in one place.

Hard caps refuse the input outright. They are sized so no realistic
phonological inventory is constrained, and so an obvious accident
(a paragraph pasted into a name field, an autogenerated 100k-segment
stress file) is rejected before it can degrade the UI, logs, or
validation reports.

Soft thresholds are not errors; they surface in the inventory's
``advisories`` so the user knows when the inventory is outside the
usual operating range. Bundled inventories stay below these so they
do not trigger advisories on every load (General, the largest
bundled, is 135 segments by 30 features).
"""

from __future__ import annotations

# Hard caps.
MAX_NAME_LENGTH: int = 256
MAX_FEATURES: int = 100
MAX_SEGMENTS: int = 1000

# A bundled inventory at MAX_SEGMENTS x MAX_FEATURES with realistic
# value tokens lands around 200 KB serialized. 50 MB is ~250x the
# largest legitimate file, so this rejects a paste-the-wrong-file
# accident or malicious payload before json.load can OOM the process.
MAX_FILE_BYTES: int = 50 * 1024 * 1024

# Soft thresholds.
ADVISORY_SEGMENT_THRESHOLD: int = 200
ADVISORY_FEATURE_THRESHOLD: int = 50
