"""Hard caps and soft advisory thresholds for inventory data.

All bounds the engine enforces live in this module so a reviewer asking
"what are the contract limits?" finds the answer in one place.

Hard caps refuse the input outright. They are sized so no realistic
phonological inventory is constrained (the largest bundled inventory
is Hayes at 141 segments × 28 features, General at 134 × 30), so
an obvious accident (a paragraph pasted into a name field, an
autogenerated 100k-segment stress file) is rejected before it can
degrade the UI, logs, or validation reports.

Soft thresholds are not errors; they surface in the inventory's
``advisories`` so the user knows when the inventory is outside the
usual operating range. Bundled inventories stay below these so they
do not trigger advisories on every load.
"""

from __future__ import annotations

# Hard caps.
MAX_NAME_LENGTH: int = 256
MAX_FEATURES: int = 40
# Sized just above the realistic ceiling: PHOIBLE's largest
# inventory is !Xoo at 161 segments and the largest bundled is
# Hayes at 141. The display surfaces are stress-verified at this
# cap (vowel chart row-fit invariant, segment-pane spillover,
# feature-pane density tiers), so anything the validator admits is
# guaranteed a non-buggy render.
MAX_SEGMENTS: int = 180

# Per-class caps, enforced wherever a grid becomes an Inventory and
# on load. Classification is feature-driven (the chart layer's
# ``group_segments`` is the single source), so these are checked by
# ``chart.consonants.validate_class_caps`` rather than the parse
# layer (data must not import chart). "Consonant" excludes tone
# letters, which group_segments routes to their own ``Tones`` class
# (counted toward MAX_SEGMENTS, never toward MAX_CONSONANTS). Sized
# to the PHOIBLE maxima the display logic is verified against: So
# has exactly 50 vowels and !Xoo has 130 consonants (plus 3 tone
# letters), the densest real charts the vowel space and segment
# pane are tested to render cleanly.
MAX_VOWELS: int = 50
MAX_CONSONANTS: int = 135

# A bundled inventory at MAX_SEGMENTS x MAX_FEATURES with realistic
# value tokens lands around 40 KB serialized. 5 MB is ~125x the
# largest legitimate file, well above any real inventory yet small
# enough that Pyodide's wasm linear-memory budget on the web side
# parses it without pressure. Shared by the desktop loader and the
# web upload pre-check (baked into the inline LIMITS JSON in
# index.html at build time) so the two surfaces agree on which
# files are out of bounds.
MAX_INVENTORY_FILE_BYTES: int = 5 * 1024 * 1024

# Soft thresholds. Sit above the largest bundled inventory (Hayes 141
# segments, General 30 features) but below the hard caps so the
# advisory has room to fire on custom inventories before they hit the
# refuse-outright limit.
ADVISORY_SEGMENT_THRESHOLD: int = 175
ADVISORY_FEATURE_THRESHOLD: int = 35
